/*
 * web_pages.c — 内嵌页面(由 gen_pages.sh 从 pages/ 生成,**不要手改**)
 *
 * 改动流程:编辑 pages/index.html|app.css|app.js → ./gen_pages.sh → 提交两个
 * 文件(生成物随仓库提交,构建机无需 python3/前端工具链)。
 */
#include "web_pages.h"

/* pages/index.html (text/html) */
const char *const DG_WEB_INDEX_HTML =
    "<!DOCTYPE html>\n"
    "<html lang=\"zh-CN\">\n"
    "<head>\n"
    "<meta charset=\"utf-8\">\n"
    "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
    "<title>door-guard 门禁上位机</title>\n"
    "<link rel=\"icon\" href=\"/favicon.ico\">\n"
    "<link rel=\"stylesheet\" href=\"/app.css\">\n"
    "</head>\n"
    "<body>\n"
    "\n"
    "<!-- ============ 登录 ============ -->\n"
    "<div class=\"login-wrap\" id=\"login-view\">\n"
    "  <form class=\"login-card\" id=\"login-form\" autocomplete=\"on\">\n"
    "    <div class=\"logo\" aria-hidden=\"true\">\n"
    "      <svg viewBox=\"0 0 64 64\" width=\"56\" height=\"56\">\n"
    "        <rect width=\"64\" height=\"64\" rx=\"16\" fill=\"url(#g)\"/>\n"
    "        <defs><linearGradient id=\"g\" x1=\"0\" y1=\"0\" x2=\"1\" y2=\"1\">\n"
    "          <stop offset=\"0\" stop-color=\"#42A5F5\"/><stop offset=\"1\" stop-color=\"#1565C0\"/>\n"
    "        </linearGradient></defs>\n"
    "        <path d=\"M20 14h16a12 12 0 0 1 0 24H20z\" fill=\"#fff\" opacity=\".95\"/>\n"
    "        <circle cx=\"43\" cy=\"47\" r=\"4.5\" fill=\"#fff\"/>\n"
    "      </svg>\n"
    "    </div>\n"
    "    <h1>door-guard</h1>\n"
    "    <p class=\"sub\">人脸识别门禁 · 上位机</p>\n"
    "    <label class=\"field\">\n"
    "      <span>账号</span>\n"
    "      <input id=\"login-user\" name=\"user\" value=\"admin\" autocomplete=\"username\" autocapitalize=\"off\">\n"
    "    </label>\n"
    "    <label class=\"field\">\n"
    "      <span>密码</span>\n"
    "      <input id=\"login-pwd\" name=\"pwd\" type=\"password\" autocomplete=\"current-password\">\n"
    "    </label>\n"
    "    <button class=\"btn primary block\" type=\"submit\" id=\"login-btn\">登 录</button>\n"
    "    <p class=\"err\" id=\"login-msg\" role=\"alert\"></p>\n"
    "  </form>\n"
    "  <p class=\"hint\">提示:设备默认账号 admin / admin,首次登录后请立即在「账号安全」中修改。</p>\n"
    "</div>\n"
    "\n"
    "<!-- ============ 主界面 ============ -->\n"
    "<div id=\"app-view\" hidden>\n"
    "  <header class=\"topbar\">\n"
    "    <div class=\"brand\">\n"
    "      <span class=\"mark\" aria-hidden=\"true\"></span>\n"
    "      <span>door-guard 门禁上位机</span>\n"
    "    </div>\n"
    "    <div class=\"topbar-right\">\n"
    "      <span class=\"conn\" id=\"conn\" title=\"实时事件连接状态\">\n"
    "        <i class=\"pulse\"></i><span id=\"conn-text\">连接中…</span>\n"
    "      </span>\n"
    "      <span class=\"who\" id=\"who\"></span>\n"
    "      <button class=\"btn ghost sm\" id=\"btn-logout\" type=\"button\">退出</button>\n"
    "    </div>\n"
    "  </header>\n"
    "\n"
    "  <div class=\"banner\" id=\"pwd-banner\" hidden>\n"
    "    <span class=\"ico\">!</span>\n"
    "    <span>当前仍是出厂默认口令,局域网内任何人都能登录。请立即修改账号与口令。</span>\n"
    "    <button class=\"btn warn sm\" id=\"btn-goto-account\" type=\"button\">去修改</button>\n"
    "  </div>\n"
    "\n"
    "  <main class=\"grid\">\n"
    "    <!-- 设备概览 -->\n"
    "    <section class=\"card span2\" style=\"--i:0\">\n"
    "      <h2>设备概览</h2>\n"
    "      <div class=\"stats\">\n"
    "        <div class=\"stat\"><span class=\"k\">固件版本</span><span class=\"v\" id=\"st-version\">—</span></div>\n"
    "        <div class=\"stat\"><span class=\"k\">运行时长</span><span class=\"v\" id=\"st-uptime\">—</span></div>\n"
    "        <div class=\"stat\"><span class=\"k\">在库用户</span><span class=\"v\" id=\"st-users\" data-count=\"0\">0</span></div>\n"
    "        <div class=\"stat\"><span class=\"k\">门禁记录</span><span class=\"v\" id=\"st-logs\" data-count=\"0\">0</span></div>\n"
    "        <div class=\"stat wide\"><span class=\"k\">局域网地址</span><span class=\"v mono\" id=\"st-addr\">—</span></div>\n"
    "        <div class=\"stat wide\"><span class=\"k\">存储</span><span class=\"v mono\" id=\"st-disk\">—</span></div>\n"
    "      </div>\n"
    "    </section>\n"
    "\n"
    "    <!-- 实时事件 -->\n"
    "    <section class=\"card\" style=\"--i:1\">\n"
    "      <h2>实时门禁事件<span class=\"badge live\" id=\"live-badge\" hidden>LIVE</span></h2>\n"
    "      <div class=\"feed\" id=\"feed\" aria-live=\"polite\">\n"
    "        <p class=\"empty\">等待验证事件…(刷脸/刷卡/输入密码后会实时出现在这里)</p>\n"
    "      </div>\n"
    "      <button class=\"btn ghost sm\" id=\"btn-clear-feed\" type=\"button\">清空</button>\n"
    "    </section>\n"
    "\n"
    "    <!-- 时间同步 -->\n"
    "    <section class=\"card\" style=\"--i:2\">\n"
    "      <h2>时间同步</h2>\n"
    "      <p class=\"muted\" id=\"ntp-state\">尚未校正</p>\n"
    "      <div class=\"clock\" id=\"clock\">--:--:--</div>\n"
    "      <button class=\"btn primary block\" id=\"btn-ntp\" type=\"button\">立即校正时间</button>\n"
    "      <p class=\"muted small\">设备需已联网;校正结果会在此处与实时事件中提示。</p>\n"
    "    </section>\n"
    "\n"
    "    <!-- 记录查询 -->\n"
    "    <section class=\"card span2\" style=\"--i:3\">\n"
    "      <h2>门禁记录查询</h2>\n"
    "      <div class=\"filters\">\n"
    "        <label class=\"field sm\"><span>开始</span><input type=\"date\" id=\"q-from\"></label>\n"
    "        <label class=\"field sm\"><span>结束</span><input type=\"date\" id=\"q-to\"></label>\n"
    "        <label class=\"field sm\"><span>用户 ID</span><input id=\"q-uid\" placeholder=\"可留空\" autocapitalize=\"off\"></label>\n"
    "        <label class=\"field sm\"><span>每页</span>\n"
    "          <select id=\"q-size\"><option>20</option><option>50</option><option>100</option></select>\n"
    "        </label>\n"
    "        <div class=\"quick\">\n"
    "          <button class=\"chip\" type=\"button\" data-range=\"today\">今天</button>\n"
    "          <button class=\"chip\" type=\"button\" data-range=\"7d\">近 7 天</button>\n"
    "          <button class=\"chip\" type=\"button\" data-range=\"all\">全部</button>\n"
    "        </div>\n"
    "        <button class=\"btn primary\" id=\"btn-query\" type=\"button\">查询</button>\n"
    "      </div>\n"
    "      <div class=\"table-wrap\">\n"
    "        <table class=\"tbl\">\n"
    "          <thead><tr><th>时间</th><th>用户 ID</th><th>姓名</th><th>方式</th><th>结果</th></tr></thead>\n"
    "          <tbody id=\"logs-body\"><tr><td colspan=\"5\" class=\"empty\">尚无记录</td></tr></tbody>\n"
    "        </table>\n"
    "      </div>\n"
    "      <div class=\"pager\">\n"
    "        <button class=\"btn ghost sm\" id=\"pg-prev\" type=\"button\">上一页</button>\n"
    "        <span class=\"muted\" id=\"pg-info\">—</span>\n"
    "        <button class=\"btn ghost sm\" id=\"pg-next\" type=\"button\">下一页</button>\n"
    "      </div>\n"
    "    </section>\n"
    "\n"
    "    <!-- 账号安全 -->\n"
    "    <section class=\"card\" style=\"--i:4\">\n"
    "      <h2>账号安全</h2>\n"
    "      <label class=\"field sm\"><span>账号</span><input id=\"ac-user\" autocapitalize=\"off\"></label>\n"
    "      <label class=\"field sm\"><span>原口令</span><input id=\"ac-old\" type=\"password\" autocomplete=\"current-password\"></label>\n"
    "      <label class=\"field sm\"><span>新口令</span><input id=\"ac-new\" type=\"password\" autocomplete=\"new-password\"></label>\n"
    "      <label class=\"field sm\"><span>确认新口令</span><input id=\"ac-confirm\" type=\"password\" autocomplete=\"new-password\"></label>\n"
    "      <button class=\"btn primary block\" id=\"btn-save-account\" type=\"button\">保存并重新登录</button>\n"
    "      <p class=\"muted small\">账号 3~31 位(字母/数字/-/_),口令 4~31 位且不能含空格;修改成功后所有会话失效。</p>\n"
    "    </section>\n"
    "\n"
    "    <!-- 固件升级 -->\n"
    "    <section class=\"card\" style=\"--i:5\">\n"
    "      <h2>固件升级</h2>\n"
    "      <p class=\"muted\">升级包由运维主机推送(校验 sha256 后写入暂存分区,不阻塞门禁业务):</p>\n"
    "      <pre class=\"code\">dg-ota-upload &lt;设备IP&gt; &lt;升级包.tar.gz&gt;</pre>\n"
    "      <p class=\"muted small\">设备侧接收端口见「设备概览 / 局域网地址」;升级完成需重启设备生效。</p>\n"
    "    </section>\n"
    "\n"
    "    <!-- 视频监控 -->\n"
    "    <section class=\"card span2\" style=\"--i:6\">\n"
    "      <h2>监控画面</h2>\n"
    "      <div class=\"video-ph\">\n"
    "        <div class=\"scanline\"></div>\n"
    "        <div class=\"video-msg\">摄像头实时画面接入中…</div>\n"
    "        <p class=\"muted small\">预览链路(RTSP / MJPEG)与取流服务对接后,此处直接显示画面,不额外占用摄像头。</p>\n"
    "      </div>\n"
    "    </section>\n"
    "  </main>\n"
    "\n"
    "  <footer class=\"foot\">\n"
    "    <span id=\"foot-ver\"></span>\n"
    "    <span class=\"muted\">door-guard · RK3576 人脸识别门禁</span>\n"
    "  </footer>\n"
    "</div>\n"
    "\n"
    "<div id=\"toasts\" class=\"toasts\" aria-live=\"polite\"></div>\n"
    "<script src=\"/app.js\"></script>\n"
    "</body>\n"
    "</html>\n"
    "";

/* pages/app.css (text/css) */
const char *const DG_WEB_APP_CSS =
    "/* app.css — 门禁上位机样式(蓝白主题,与设备端 theme.h 同色调)\n"
    " *\n"
    " * 组织:变量 → 基础 → 按钮/表单 → 卡片 → 各区块 → 动效 → 响应式/无障碍。\n"
    " * 动效纪律:只动 transform/opacity(合成器友好,ARM 板子自带浏览器也不掉帧),\n"
    " * 且尊重 prefers-reduced-motion。\n"
    " */\n"
    ":root{\n"
    "  --primary:#1E88E5; --primary-dark:#1565C0; --primary-light:#E3F2FD;\n"
    "  --bg:#F4F8FD; --card:#FFFFFF; --text:#212121; --muted:#6B7A8C;\n"
    "  --ok:#2E7D32; --err:#C62828; --warn:#F9A825; --line:#E1EAF4;\n"
    "  --radius:14px; --shadow:0 2px 10px rgba(21,101,192,.08);\n"
    "  --shadow-hover:0 8px 24px rgba(21,101,192,.16);\n"
    "}\n"
    "*{box-sizing:border-box}\n"
    "html,body{margin:0;padding:0}\n"
    "body{\n"
    "  font-family:system-ui,-apple-system,\"Segoe UI\",\"Noto Sans SC\",\"PingFang SC\",\"Microsoft YaHei\",sans-serif;\n"
    "  background:var(--bg); color:var(--text); line-height:1.55;\n"
    "  -webkit-font-smoothing:antialiased;\n"
    "}\n"
    "h1{font-size:24px;margin:6px 0 2px}\n"
    "h2{font-size:16px;margin:0 0 12px;display:flex;align-items:center;gap:8px}\n"
    "h2::before{content:\"\";width:4px;height:16px;border-radius:2px;background:var(--primary)}\n"
    ".muted{color:var(--muted)}\n"
    ".small{font-size:12px}\n"
    ".mono{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace}\n"
    ".empty{color:var(--muted);text-align:center;padding:18px 0}\n"
    "\n"
    "/* ---------- 登录 ---------- */\n"
    ".login-wrap{\n"
    "  min-height:100vh;display:flex;flex-direction:column;align-items:center;justify-content:center;\n"
    "  gap:14px;padding:24px;\n"
    "  background:radial-gradient(1200px 600px at 50% -10%,#DCEBFA 0%,var(--bg) 60%);\n"
    "}\n"
    ".login-card{\n"
    "  width:100%;max-width:360px;background:var(--card);border-radius:18px;padding:28px 26px;\n"
    "  box-shadow:0 12px 40px rgba(21,101,192,.14);\n"
    "  display:flex;flex-direction:column;gap:12px;\n"
    "  animation:rise .5s cubic-bezier(.2,.8,.3,1) both;\n"
    "}\n"
    ".login-card.shake{animation:shake .4s}\n"
    ".logo{display:flex;justify-content:center;filter:drop-shadow(0 6px 12px rgba(30,136,229,.32))}\n"
    ".login-card h1{text-align:center;color:var(--primary-dark);letter-spacing:.5px}\n"
    ".login-card .sub{text-align:center;color:var(--muted);margin:0 0 8px;font-size:13px}\n"
    ".hint{max-width:360px;text-align:center;color:var(--muted);font-size:12px;margin:0}\n"
    "\n"
    "/* ---------- 按钮 ---------- */\n"
    ".btn{\n"
    "  border:0;border-radius:10px;padding:10px 18px;font-size:14px;font-weight:600;cursor:pointer;\n"
    "  color:#fff;background:linear-gradient(180deg,var(--primary),var(--primary-dark));\n"
    "  transition:transform .12s,box-shadow .2s,filter .2s;\n"
    "  position:relative;overflow:hidden;\n"
    "}\n"
    ".btn:hover{box-shadow:var(--shadow-hover);filter:brightness(1.04)}\n"
    ".btn:active{transform:translateY(1px) scale(.99)}\n"
    ".btn[disabled]{opacity:.55;cursor:not-allowed;transform:none;box-shadow:none}\n"
    ".btn.block{width:100%}\n"
    ".btn.sm{padding:6px 12px;font-size:13px}\n"
    ".btn.ghost{background:transparent;color:var(--primary-dark);border:1px solid var(--line)}\n"
    ".btn.ghost:hover{background:var(--primary-light)}\n"
    ".btn.warn{background:linear-gradient(180deg,#FFB300,#F57F17)}\n"
    ".btn.primary{background:linear-gradient(180deg,var(--primary),var(--primary-dark))}\n"
    ".ripple{position:absolute;border-radius:50%;transform:scale(0);animation:ripple .55s linear;\n"
    "  background:rgba(255,255,255,.55);pointer-events:none}\n"
    ".chip{\n"
    "  border:1px solid var(--line);background:#fff;color:var(--primary-dark);\n"
    "  border-radius:999px;padding:5px 12px;font-size:12px;cursor:pointer;transition:all .18s;\n"
    "}\n"
    ".chip:hover{border-color:var(--primary);background:var(--primary-light)}\n"
    ".chip.on{background:var(--primary);color:#fff;border-color:var(--primary)}\n"
    "\n"
    "/* ---------- 表单 ---------- */\n"
    ".field{display:flex;flex-direction:column;gap:4px;font-size:13px;color:var(--muted)}\n"
    ".field span{font-weight:600}\n"
    ".field input,.field select{\n"
    "  padding:10px 12px;border:1px solid var(--line);border-radius:10px;font-size:14px;color:var(--text);\n"
    "  background:#FBFDFF;transition:border-color .18s,box-shadow .18s;width:100%;\n"
    "}\n"
    ".field input:focus,.field select:focus{\n"
    "  outline:none;border-color:var(--primary);box-shadow:0 0 0 3px rgba(30,136,229,.15);background:#fff;\n"
    "}\n"
    ".field.sm input,.field.sm select{padding:7px 10px;font-size:13px}\n"
    "\n"
    "/* ---------- 顶栏 ---------- */\n"
    ".topbar{\n"
    "  position:sticky;top:0;z-index:20;display:flex;align-items:center;justify-content:space-between;\n"
    "  gap:12px;padding:12px 18px;color:#fff;\n"
    "  background:linear-gradient(115deg,#1565C0,#1E88E5 45%,#42A5F5);\n"
    "  background-size:200% 100%;animation:flow 14s ease-in-out infinite;\n"
    "  box-shadow:0 2px 12px rgba(21,101,192,.25);\n"
    "}\n"
    ".brand{display:flex;align-items:center;gap:9px;font-weight:700;font-size:16px}\n"
    ".mark{width:14px;height:14px;border-radius:4px;background:#fff;box-shadow:0 0 0 3px rgba(255,255,255,.35)}\n"
    ".topbar-right{display:flex;align-items:center;gap:12px;font-size:13px}\n"
    ".conn{display:flex;align-items:center;gap:6px;background:rgba(255,255,255,.16);\n"
    "  padding:4px 10px;border-radius:999px}\n"
    ".pulse{width:8px;height:8px;border-radius:50%;background:#9E9E9E;position:relative}\n"
    ".conn.on .pulse{background:#7CFC9A}\n"
    ".conn.on .pulse::after{\n"
    "  content:\"\";position:absolute;inset:-4px;border-radius:50%;border:2px solid #7CFC9A;\n"
    "  animation:ring 1.6s ease-out infinite;\n"
    "}\n"
    ".conn.off .pulse{background:#FFAB91}\n"
    ".who{opacity:.9}\n"
    "\n"
    "/* ---------- 布局 ---------- */\n"
    ".grid{\n"
    "  display:grid;gap:16px;padding:16px;max-width:1180px;margin:0 auto;\n"
    "  grid-template-columns:repeat(auto-fit,minmax(320px,1fr));\n"
    "}\n"
    ".card{\n"
    "  background:var(--card);border-radius:var(--radius);padding:18px;box-shadow:var(--shadow);\n"
    "  border:1px solid var(--line);\n"
    "  animation:rise .45s cubic-bezier(.2,.8,.3,1) both;\n"
    "  animation-delay:calc(var(--i,0) * 70ms);\n"
    "  transition:box-shadow .25s,transform .25s;\n"
    "}\n"
    ".card:hover{box-shadow:var(--shadow-hover);transform:translateY(-2px)}\n"
    ".card.span2{grid-column:span 2}\n"
    "@media(max-width:820px){.card.span2{grid-column:span 1}}\n"
    "\n"
    "/* ---------- 概览数字 ---------- */\n"
    ".stats{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:12px}\n"
    ".stat{background:linear-gradient(180deg,#FAFCFF,var(--primary-light));border-radius:12px;\n"
    "  padding:12px 14px;display:flex;flex-direction:column;gap:2px;border:1px solid #E8F1FB}\n"
    ".stat .k{font-size:12px;color:var(--muted)}\n"
    ".stat .v{font-size:19px;font-weight:700;color:var(--primary-dark)}\n"
    ".stat .v.mono{font-size:14px;font-weight:600;word-break:break-all}\n"
    ".stat.wide{grid-column:span 2}\n"
    "\n"
    "/* ---------- 实时事件 ---------- */\n"
    ".badge{font-size:10px;padding:2px 7px;border-radius:999px;background:var(--err);color:#fff;\n"
    "  letter-spacing:.5px}\n"
    ".badge.live{animation:blink 1.6s ease-in-out infinite}\n"
    ".feed{max-height:320px;overflow:auto;display:flex;flex-direction:column;gap:8px;margin-bottom:10px}\n"
    ".ev{\n"
    "  display:flex;align-items:center;gap:10px;padding:9px 12px;border-radius:10px;\n"
    "  background:#F7FBFF;border-left:4px solid var(--primary);font-size:13px;\n"
    "  animation:slideIn .38s cubic-bezier(.2,.8,.3,1) both;\n"
    "}\n"
    ".ev.ok{border-left-color:var(--ok);background:#F2FBF3}\n"
    ".ev.err{border-left-color:var(--err);background:#FDF3F3}\n"
    ".ev .t{color:var(--muted);font-size:12px;min-width:132px}\n"
    ".ev .n{font-weight:700}\n"
    ".ev .pill{margin-left:auto;padding:2px 9px;border-radius:999px;font-size:11px;color:#fff;\n"
    "  background:var(--primary)}\n"
    ".ev.ok .pill{background:var(--ok)}\n"
    ".ev.err .pill{background:var(--err)}\n"
    "\n"
    "/* ---------- 时间 ---------- */\n"
    ".clock{font-size:34px;font-weight:700;color:var(--primary-dark);letter-spacing:2px;\n"
    "  font-variant-numeric:tabular-nums;margin:6px 0 14px}\n"
    "\n"
    "/* ---------- 表格 ---------- */\n"
    ".filters{display:flex;flex-wrap:wrap;gap:10px;align-items:flex-end;margin-bottom:12px}\n"
    ".filters .field{min-width:130px}\n"
    ".quick{display:flex;gap:6px}\n"
    ".table-wrap{overflow-x:auto;border-radius:10px;border:1px solid var(--line)}\n"
    ".tbl{width:100%;border-collapse:collapse;font-size:13px}\n"
    ".tbl th{background:var(--primary-light);color:var(--primary-dark);text-align:left;\n"
    "  padding:10px;font-weight:700;position:sticky;top:0}\n"
    ".tbl td{padding:9px 10px;border-top:1px solid var(--line)}\n"
    ".tbl tbody tr{transition:background .15s}\n"
    ".tbl tbody tr:hover{background:#F5FAFF}\n"
    ".tbl tr.row-anim{animation:fadeIn .3s both}\n"
    ".res{display:inline-block;padding:1px 9px;border-radius:999px;font-size:12px;font-weight:600}\n"
    ".res.pass{background:#E8F5E9;color:var(--ok)}\n"
    ".res.deny{background:#FDECEA;color:var(--err)}\n"
    ".pager{display:flex;align-items:center;justify-content:center;gap:12px;margin-top:12px}\n"
    "\n"
    "/* ---------- 视频占位 ---------- */\n"
    ".video-ph{position:relative;height:210px;border-radius:12px;overflow:hidden;\n"
    "  background:linear-gradient(135deg,#0F2027,#203A43,#2C5364);display:flex;flex-direction:column;\n"
    "  align-items:center;justify-content:center;color:#CFE8FF;gap:6px;text-align:center;padding:16px}\n"
    ".scanline{position:absolute;left:0;right:0;height:40px;\n"
    "  background:linear-gradient(180deg,transparent,rgba(66,165,245,.35),transparent);\n"
    "  animation:scan 3.4s linear infinite}\n"
    ".video-msg{font-size:15px;font-weight:600;z-index:1}\n"
    ".code{background:#0F172A;color:#B3E5FC;border-radius:10px;padding:12px;font-size:13px;\n"
    "  overflow-x:auto;margin:8px 0}\n"
    ".foot{display:flex;justify-content:space-between;gap:10px;flex-wrap:wrap;\n"
    "  padding:16px 20px 28px;max-width:1180px;margin:0 auto;font-size:12px;color:var(--muted)}\n"
    "\n"
    "/* ---------- 横幅 / 提示 ---------- */\n"
    ".banner{display:flex;align-items:center;gap:12px;margin:14px auto 0;max-width:1180px;\n"
    "  padding:12px 16px;border-radius:12px;background:#FFF8E1;border:1px solid #FFE082;\n"
    "  color:#8D6E00;font-size:13px;animation:rise .4s both}\n"
    ".banner .ico{width:22px;height:22px;border-radius:50%;background:var(--warn);color:#fff;\n"
    "  display:grid;place-items:center;font-weight:700;flex:0 0 auto}\n"
    ".banner .btn{margin-left:auto}\n"
    ".toasts{position:fixed;right:18px;bottom:18px;display:flex;flex-direction:column;gap:10px;z-index:50}\n"
    ".toast{background:#fff;border-left:4px solid var(--primary);border-radius:10px;padding:11px 16px;\n"
    "  box-shadow:0 8px 24px rgba(21,101,192,.18);font-size:13px;min-width:220px;\n"
    "  animation:toastIn .32s cubic-bezier(.2,.8,.3,1) both}\n"
    ".toast.ok{border-left-color:var(--ok)}\n"
    ".toast.err{border-left-color:var(--err)}\n"
    ".toast.out{animation:toastOut .28s both}\n"
    ".err{color:var(--err);font-size:13px;min-height:18px;margin:0}\n"
    "\n"
    "/* ---------- 动效 ---------- */\n"
    "@keyframes rise{from{opacity:0;transform:translateY(14px)}to{opacity:1;transform:none}}\n"
    "@keyframes fadeIn{from{opacity:0}to{opacity:1}}\n"
    "@keyframes slideIn{from{opacity:0;transform:translateX(-14px)}to{opacity:1;transform:none}}\n"
    "@keyframes toastIn{from{opacity:0;transform:translateX(24px) scale(.96)}to{opacity:1;transform:none}}\n"
    "@keyframes toastOut{to{opacity:0;transform:translateX(24px) scale(.96)}}\n"
    "@keyframes ripple{to{transform:scale(2.6);opacity:0}}\n"
    "@keyframes ring{0%{transform:scale(.7);opacity:.9}100%{transform:scale(1.7);opacity:0}}\n"
    "@keyframes blink{0%,100%{opacity:1}50%{opacity:.35}}\n"
    "@keyframes flow{0%,100%{background-position:0 50%}50%{background-position:100% 50%}}\n"
    "@keyframes scan{0%{top:-40px}100%{top:100%}}\n"
    "@keyframes shake{0%,100%{transform:translateX(0)}20%{transform:translateX(-8px)}\n"
    "  40%{transform:translateX(8px)}60%{transform:translateX(-5px)}80%{transform:translateX(5px)}}\n"
    "@media(prefers-reduced-motion:reduce){\n"
    "  *{animation-duration:.001ms!important;animation-iteration-count:1!important;transition:none!important}\n"
    "}\n"
    "";

/* pages/app.js (application/javascript) */
const char *const DG_WEB_APP_JS =
    "/* app.js — 门禁上位机前端逻辑(零依赖,单文件)\n"
    " *\n"
    " * 结构:状态 → 工具(fetch/提示/数字动画) → 登录 → 概览 → 实时事件(WS)\n"
    " *       → 记录查询 → 时间同步 → 账号安全 → 启动流程。\n"
    " * 纪律:\n"
    " *   - 所有接口调用经 api():统一带 token、统一处理 401(掉线回登录页)\n"
    " *   - WebSocket 断线自动重连(退避),状态在顶栏可见\n"
    " *   - 时间/姓名等文本一律用 textContent 或转义写入,不用 innerHTML 拼数据\n"
    " *     (用户姓名是用户可控字段,拼 HTML 就是自造 XSS)\n"
    " */\n"
    "'use strict';\n"
    "\n"
    "const $ = (id) => document.getElementById(id);\n"
    "const TOKEN_KEY = 'dg_token';\n"
    "\n"
    "const S = {\n"
    "  token: sessionStorage.getItem(TOKEN_KEY) || '',\n"
    "  user: '',\n"
    "  page: 1,\n"
    "  pages: 1,\n"
    "  ws: null,\n"
    "  wsTries: 0,\n"
    "  ntpPending: false,\n"
    "};\n"
    "\n"
    "/* ---------------- 工具 ---------------- */\n"
    "\n"
    "function toast(msg, kind) {\n"
    "  const box = document.createElement('div');\n"
    "  box.className = 'toast ' + (kind || '');\n"
    "  box.textContent = msg;\n"
    "  $('toasts').appendChild(box);\n"
    "  setTimeout(() => {\n"
    "    box.classList.add('out');\n"
    "    setTimeout(() => box.remove(), 300);\n"
    "  }, kind === 'err' ? 5200 : 3200);\n"
    "}\n"
    "\n"
    "function esc(s) {\n"
    "  return String(s == null ? '' : s);\n"
    "}\n"
    "\n"
    "/* 数字滚动:只对变化的数值生效,避免每次刷新都跳 */\n"
    "function countUp(el, to) {\n"
    "  const from = Number(el.dataset.count || 0);\n"
    "  if (from === to) { el.textContent = to; return; }\n"
    "  el.dataset.count = to;\n"
    "  const steps = 18;\n"
    "  let i = 0;\n"
    "  const timer = setInterval(() => {\n"
    "    i++;\n"
    "    const v = Math.round(from + (to - from) * (i / steps));\n"
    "    el.textContent = v;\n"
    "    if (i >= steps) clearInterval(timer);\n"
    "  }, 24);\n"
    "}\n"
    "\n"
    "function fmtBytes(n) {\n"
    "  if (!n) return '—';\n"
    "  const u = ['B', 'KB', 'MB', 'GB'];\n"
    "  let i = 0, v = n;\n"
    "  while (v >= 1024 && i < u.length - 1) { v /= 1024; i++; }\n"
    "  return v.toFixed(v < 10 && i > 0 ? 1 : 0) + ' ' + u[i];\n"
    "}\n"
    "\n"
    "async function api(path, opts) {\n"
    "  opts = opts || {};\n"
    "  const headers = Object.assign({}, opts.headers || {});\n"
    "  if (S.token) headers['X-Auth-Token'] = S.token;\n"
    "  if (opts.body) headers['Content-Type'] = 'application/json';\n"
    "  const res = await fetch(path, Object.assign({}, opts, { headers }));\n"
    "  let data = null;\n"
    "  try { data = await res.json(); } catch (e) { data = null; }\n"
    "  if (res.status === 401) {\n"
    "    logout(false);\n"
    "    showLogin((data && data.msg) || '会话已过期,请重新登录');\n"
    "    throw new Error('unauthorized');\n"
    "  }\n"
    "  if (!res.ok) {\n"
    "    const msg = (data && data.msg) || ('请求失败(' + res.status + ')');\n"
    "    throw new Error(msg);\n"
    "  }\n"
    "  return data || {};\n"
    "}\n"
    "\n"
    "/* 按钮水波纹(纯装饰:pointerdown 时插一个扩散圆) */\n"
    "document.addEventListener('pointerdown', (e) => {\n"
    "  const btn = e.target.closest('.btn');\n"
    "  if (!btn) return;\n"
    "  const r = btn.getBoundingClientRect();\n"
    "  const span = document.createElement('span');\n"
    "  const size = Math.max(r.width, r.height);\n"
    "  span.className = 'ripple';\n"
    "  span.style.width = span.style.height = size + 'px';\n"
    "  span.style.left = (e.clientX - r.left - size / 2) + 'px';\n"
    "  span.style.top = (e.clientY - r.top - size / 2) + 'px';\n"
    "  btn.appendChild(span);\n"
    "  setTimeout(() => span.remove(), 600);\n"
    "});\n"
    "\n"
    "/* ---------------- 登录/登出 ---------------- */\n"
    "\n"
    "function showLogin(msg) {\n"
    "  $('app-view').hidden = true;\n"
    "  $('login-view').style.display = '';\n"
    "  if (msg) {\n"
    "    $('login-msg').textContent = msg;\n"
    "    const card = $('login-form');\n"
    "    card.classList.remove('shake');\n"
    "    void card.offsetWidth;                 /* 强制重排:同一动画可重复触发 */\n"
    "    card.classList.add('shake');\n"
    "  }\n"
    "  $('login-pwd').focus();\n"
    "}\n"
    "\n"
    "function logout(notify) {\n"
    "  if (S.token) {\n"
    "    const t = S.token;\n"
    "    S.token = '';\n"
    "    sessionStorage.removeItem(TOKEN_KEY);\n"
    "    fetch('/api/logout', { method: 'POST', headers: { 'X-Auth-Token': t } })\n"
    "      .catch(() => {});\n"
    "  }\n"
    "  if (S.ws) { try { S.ws.close(); } catch (e) {} S.ws = null; }\n"
    "  if (notify) toast('已退出登录');\n"
    "}\n"
    "\n"
    "$('login-form').addEventListener('submit', async (e) => {\n"
    "  e.preventDefault();\n"
    "  const btn = $('login-btn');\n"
    "  btn.disabled = true;\n"
    "  $('login-msg').textContent = '';\n"
    "  try {\n"
    "    const r = await fetch('/api/login', {\n"
    "      method: 'POST',\n"
    "      headers: { 'Content-Type': 'application/json' },\n"
    "      body: JSON.stringify({ user: $('login-user').value, pwd: $('login-pwd').value }),\n"
    "    });\n"
    "    const j = await r.json().catch(() => ({}));\n"
    "    if (!r.ok) throw new Error(j.msg || '登录失败');\n"
    "    S.token = j.token;\n"
    "    S.user = j.user || '';\n"
    "    sessionStorage.setItem(TOKEN_KEY, S.token);\n"
    "    $('login-pwd').value = '';\n"
    "    $('pwd-banner').hidden = !j.pwd_default;\n"
    "    boot();\n"
    "    toast('登录成功,欢迎 ' + esc(S.user), 'ok');\n"
    "  } catch (err) {\n"
    "    $('login-msg').textContent = err.message;\n"
    "    const card = $('login-form');\n"
    "    card.classList.remove('shake');\n"
    "    void card.offsetWidth;\n"
    "    card.classList.add('shake');\n"
    "  } finally {\n"
    "    btn.disabled = false;\n"
    "  }\n"
    "});\n"
    "\n"
    "$('btn-logout').addEventListener('click', () => { logout(true); showLogin(''); });\n"
    "\n"
    "/* ---------------- 设备概览 ---------------- */\n"
    "\n"
    "async function loadDevice() {\n"
    "  const d = await api('/api/device');\n"
    "  $('st-version').textContent = d.version || '—';\n"
    "  $('st-uptime').textContent = d.uptime_text || (d.uptime_s + 's');\n"
    "  countUp($('st-users'), d.users || 0);\n"
    "  countUp($('st-logs'), d.log_total || 0);\n"
    "  $('st-addr').textContent = d.mdns_running\n"
    "    ? 'http://' + d.mdns_host + '.local:' + d.web_port + '  ·  ' +\n"
    "      (d.ip ? d.ip + ':' + d.web_port : '无 IP')\n"
    "    : (d.ip ? 'http://' + d.ip + ':' + d.web_port : '设备未联网');\n"
    "  $('st-disk').textContent = '库 ' + fmtBytes(d.db_bytes) + ' / 余 ' + fmtBytes(d.disk_free_bytes);\n"
    "  $('foot-ver').textContent = '固件 ' + (d.version || '—');\n"
    "  if (d.ntp && d.ntp.ok && d.ntp.last_ok_at) {\n"
    "    $('ntp-state').textContent = '上次校正成功:' + d.ntp.last_ok_at;\n"
    "  }\n"
    "  S.online = !!d.online;\n"
    "  syncNtpBtn();\n"
    "  S.user = d.web_user || S.user;\n"
    "  $('who').textContent = S.user ? ('管理员 ' + S.user) : '';\n"
    "  $('ac-user').value = S.user;\n"
    "  $('pwd-banner').hidden = !d.pwd_default;\n"
    "  return d;\n"
    "}\n"
    "\n"
    "/* ---------------- 实时事件(WebSocket) ---------------- */\n"
    "\n"
    "function setConn(on, text) {\n"
    "  const el = $('conn');\n"
    "  el.classList.toggle('on', !!on);\n"
    "  el.classList.toggle('off', !on);\n"
    "  $('conn-text').textContent = text;\n"
    "  $('live-badge').hidden = !on;\n"
    "}\n"
    "\n"
    "function connectWS() {\n"
    "  const proto = location.protocol === 'https:' ? 'wss://' : 'ws://';\n"
    "  const url = proto + location.host + '/api/ws?token=' + encodeURIComponent(S.token);\n"
    "  let ws;\n"
    "  try { ws = new WebSocket(url); } catch (e) { setConn(false, '不支持'); return; }\n"
    "  S.ws = ws;\n"
    "  ws.onopen = () => { S.wsTries = 0; setConn(true, '实时连接'); };\n"
    "  ws.onclose = () => {\n"
    "    setConn(false, '已断开');\n"
    "    if (!S.token) return;                   /* 主动退出:不重连 */\n"
    "    S.wsTries++;\n"
    "    const delay = Math.min(15000, 800 * Math.pow(1.6, S.wsTries));\n"
    "    setConn(false, '重连中…');\n"
    "    /* 连不上多半是服务端会话已失效(重启/改密):探一次接口,401 会\n"
    "     * 走 api() 的统一处理回登录页,而不是让用户一直看\"重连中\" */\n"
    "    if (S.wsTries === 2 && S.token) {\n"
    "      api('/api/device').catch(() => {});\n"
    "    }\n"
    "    setTimeout(connectWS, delay);\n"
    "  };\n"
    "  ws.onerror = () => setConn(false, '连接异常');\n"
    "  ws.onmessage = (ev) => {\n"
    "    let j;\n"
    "    try { j = JSON.parse(ev.data); } catch (e) { return; }\n"
    "    if (j.type === 'auth') addEvent(j);\n"
    "    else if (j.type === 'ntp') {\n"
    "      S.ntpPending = false;\n"
    "      syncNtpBtn();\n"
    "      if (j.ok) $('ntp-state').textContent = '上次校正成功:' + j.time;\n"
    "      toast(j.msg || (j.ok ? '时间校正成功' : '时间校正失败'), j.ok ? 'ok' : 'err');\n"
    "      loadDevice().catch(() => {});\n"
    "    }\n"
    "  };\n"
    "}\n"
    "\n"
    "function addEvent(j) {\n"
    "  const feed = $('feed');\n"
    "  const ph = feed.querySelector('.empty');\n"
    "  if (ph) ph.remove();\n"
    "\n"
    "  const pass = Number(j.result) === 0;\n"
    "  const row = document.createElement('div');\n"
    "  row.className = 'ev ' + (pass ? 'ok' : 'err');\n"
    "\n"
    "  const t = document.createElement('span');\n"
    "  t.className = 't';\n"
    "  t.textContent = j.time || '';\n"
    "  const n = document.createElement('span');\n"
    "  n.className = 'n';\n"
    "  n.textContent = j.user_name || '陌生人';\n"
    "  const m = document.createElement('span');\n"
    "  m.className = 'muted small';\n"
    "  m.textContent = (j.user_id ? 'ID ' + j.user_id + ' · ' : '') + (j.method_name || '');\n"
    "  const p = document.createElement('span');\n"
    "  p.className = 'pill';\n"
    "  p.textContent = pass ? '通过' : '拒绝';\n"
    "\n"
    "  row.append(t, n, m, p);\n"
    "  feed.insertBefore(row, feed.firstChild);\n"
    "  while (feed.children.length > 60) feed.removeChild(feed.lastChild);\n"
    "  countUp($('st-logs'), Number($('st-logs').dataset.count || 0) + 1);\n"
    "}\n"
    "\n"
    "$('btn-clear-feed').addEventListener('click', () => {\n"
    "  $('feed').innerHTML = '<p class=\"empty\">等待验证事件…</p>';\n"
    "});\n"
    "\n"
    "/* ---------------- 记录查询 ---------------- */\n"
    "\n"
    "const dateStr = (d) => d.toISOString().slice(0, 10);\n"
    "\n"
    "document.querySelectorAll('.chip[data-range]').forEach((chip) => {\n"
    "  chip.addEventListener('click', () => {\n"
    "    document.querySelectorAll('.chip[data-range]').forEach((c) => c.classList.remove('on'));\n"
    "    chip.classList.add('on');\n"
    "    const r = chip.dataset.range;\n"
    "    const today = new Date();\n"
    "    if (r === 'today') {\n"
    "      $('q-from').value = dateStr(today);\n"
    "      $('q-to').value = dateStr(today);\n"
    "    } else if (r === '7d') {\n"
    "      const from = new Date(today.getTime() - 6 * 86400000);\n"
    "      $('q-from').value = dateStr(from);\n"
    "      $('q-to').value = dateStr(today);\n"
    "    } else {\n"
    "      $('q-from').value = '';\n"
    "      $('q-to').value = '';\n"
    "    }\n"
    "    loadLogs(1);\n"
    "  });\n"
    "});\n"
    "\n"
    "async function loadLogs(page) {\n"
    "  S.page = page || S.page || 1;\n"
    "  const body = $('logs-body');\n"
    "  body.innerHTML = '<tr><td colspan=\"5\" class=\"empty\">查询中…</td></tr>';\n"
    "  const q = new URLSearchParams();\n"
    "  if ($('q-from').value) q.set('from', $('q-from').value);\n"
    "  if ($('q-to').value) q.set('to', $('q-to').value);\n"
    "  if ($('q-uid').value.trim()) q.set('user_id', $('q-uid').value.trim());\n"
    "  q.set('page', S.page);\n"
    "  q.set('page_size', $('q-size').value);\n"
    "\n"
    "  try {\n"
    "    const d = await api('/api/logs?' + q.toString());\n"
    "    S.pages = d.pages || 1;\n"
    "    body.innerHTML = '';\n"
    "    if (!d.logs || !d.logs.length) {\n"
    "      body.innerHTML = '<tr><td colspan=\"5\" class=\"empty\">该条件下没有记录</td></tr>';\n"
    "    } else {\n"
    "      d.logs.forEach((l, idx) => {\n"
    "        const tr = document.createElement('tr');\n"
    "        tr.className = 'row-anim';\n"
    "        tr.style.animationDelay = (idx * 18) + 'ms';\n"
    "        [l.time, l.user_id || '—', l.user_name || '陌生人', l.method_name].forEach((v) => {\n"
    "          const td = document.createElement('td');\n"
    "          td.textContent = v;\n"
    "          tr.appendChild(td);\n"
    "        });\n"
    "        const td = document.createElement('td');\n"
    "        const sp = document.createElement('span');\n"
    "        const pass = Number(l.result) === 0;\n"
    "        sp.className = 'res ' + (pass ? 'pass' : 'deny');\n"
    "        sp.textContent = pass ? '通过' : '拒绝';\n"
    "        td.appendChild(sp);\n"
    "        tr.appendChild(td);\n"
    "        body.appendChild(tr);\n"
    "      });\n"
    "    }\n"
    "    $('pg-info').textContent = '第 ' + d.page + ' / ' + (d.pages || 1) +\n"
    "      ' 页 · 共 ' + d.total + ' 条';\n"
    "    $('pg-prev').disabled = d.page <= 1;\n"
    "    $('pg-next').disabled = d.page >= (d.pages || 1);\n"
    "  } catch (err) {\n"
    "    body.innerHTML = '<tr><td colspan=\"5\" class=\"empty\">查询失败:' + esc(err.message) + '</td></tr>';\n"
    "  }\n"
    "}\n"
    "\n"
    "$('btn-query').addEventListener('click', () => loadLogs(1));\n"
    "$('pg-prev').addEventListener('click', () => loadLogs(Math.max(1, S.page - 1)));\n"
    "$('pg-next').addEventListener('click', () => loadLogs(Math.min(S.pages, S.page + 1)));\n"
    "$('q-uid').addEventListener('keydown', (e) => { if (e.key === 'Enter') loadLogs(1); });\n"
    "\n"
    "/* ---------------- 时间同步 ---------------- */\n"
    "\n"
    "/* NTP 按钮可用性:未联网(或正在校正)就置灰,并说明原因 */\n"
    "function syncNtpBtn() {\n"
    "  const btn = $('btn-ntp');\n"
    "  btn.disabled = S.ntpPending || !S.online;\n"
    "  if (!S.online) $('ntp-state').textContent = '设备未联网,时间校正不可用';\n"
    "}\n"
    "\n"
    "$('btn-ntp').addEventListener('click', async () => {\n"
    "  if (S.ntpPending) return;\n"
    "  S.ntpPending = true;\n"
    "  $('btn-ntp').disabled = true;\n"
    "  try {\n"
    "    await api('/api/ntp', { method: 'POST' });\n"
    "    $('ntp-state').textContent = '校正中…(约需 5~15 秒)';\n"
    "    toast('已发起时间校正,结果稍后提示');\n"
    "  } catch (err) {\n"
    "    S.ntpPending = false;\n"
    "    syncNtpBtn();\n"
    "    toast(err.message, 'err');\n"
    "  }\n"
    "});\n"
    "\n"
    "setInterval(() => {\n"
    "  const d = new Date();\n"
    "  $('clock').textContent = [d.getHours(), d.getMinutes(), d.getSeconds()]\n"
    "    .map((v) => String(v).padStart(2, '0')).join(':');\n"
    "}, 1000);\n"
    "\n"
    "/* ---------------- 账号安全 ---------------- */\n"
    "\n"
    "$('btn-save-account').addEventListener('click', async () => {\n"
    "  const user = $('ac-user').value.trim();\n"
    "  const oldPwd = $('ac-old').value;\n"
    "  const pwd = $('ac-new').value;\n"
    "  const confirm = $('ac-confirm').value;\n"
    "  if (pwd !== confirm) { toast('两次输入的新口令不一致', 'err'); return; }\n"
    "  if (!oldPwd) { toast('请先输入原口令', 'err'); return; }\n"
    "  try {\n"
    "    const r = await api('/api/account', {\n"
    "      method: 'POST',\n"
    "      body: JSON.stringify({ user: user, old_pwd: oldPwd, pwd: pwd }),\n"
    "    });\n"
    "    toast(r.msg || '已保存', 'ok');\n"
    "    $('ac-old').value = $('ac-new').value = $('ac-confirm').value = '';\n"
    "    logout(false);\n"
    "    showLogin('凭据已修改,请用新账号口令登录');\n"
    "  } catch (err) {\n"
    "    toast(err.message, 'err');\n"
    "  }\n"
    "});\n"
    "\n"
    "$('btn-goto-account').addEventListener('click', () => {\n"
    "  $('ac-user').focus();\n"
    "  $('ac-user').scrollIntoView({ behavior: 'smooth', block: 'center' });\n"
    "});\n"
    "$('pwd-banner').hidden = true;\n"
    "\n"
    "/* ---------------- 启动 ---------------- */\n"
    "\n"
    "function boot() {\n"
    "  $('login-view').style.display = 'none';\n"
    "  $('app-view').hidden = false;\n"
    "  loadDevice().catch((e) => toast(e.message, 'err'));\n"
    "  loadLogs(1);\n"
    "  connectWS();\n"
    "  setInterval(() => { loadDevice().catch(() => {}); }, 30000);\n"
    "}\n"
    "\n"
    "if (S.token) {\n"
    "  boot();\n"
    "} else {\n"
    "  showLogin('');\n"
    "}\n"
    "";
