#include "web_pages.h"

const char *const DG_WEB_INDEX_HTML =
"<!DOCTYPE html><html><head><meta charset='utf-8'>"
"<title>door-guard 上位机</title><style>"
"body{font-family:sans-serif;margin:0;background:#fff;color:#212121}"
"header{background:#1E88E5;color:#fff;padding:12px 20px;font-size:20px}"
".card{background:#E3F2FD;border-radius:8px;margin:12px;padding:14px}"
"button{background:#1E88E5;color:#fff;border:0;border-radius:6px;"
"padding:8px 16px;cursor:pointer}button:active{background:#1565C0}"
"input{padding:8px;border:1px solid #90CAF9;border-radius:4px;margin:4px}"
"table{width:100%;border-collapse:collapse}td,th{padding:6px;border-bottom:1px solid #ddd}"
".ok{color:#2E7D32}.err{color:#C62828}#login{max-width:320px;margin:80px auto}"
"#app{display:none}</style></head><body>"
"<header>door-guard 门禁上位机 <span id='ws' style='float:right;font-size:12px'></span></header>"
"<div id='login' class='card'><h3>登录</h3>"
"用户:<input id='u' value='admin'><br>密码:<input id='p' type='password'><br>"
"<button onclick='login()'>登录</button><span id='lm' class='err'></span></div>"
"<div id='app'>"
"<div class='card'><b>实时门禁事件</b><div id='live'>—</div></div>"
"<div class='card'><b>日志查询</b>"
"开始:<input id='from' type='date'> 结束:<input id='to' type='date'>"
"<button onclick='loadLogs()'>查询</button>"
"<table id='logs'><tr><th>时间</th><th>ID</th><th>姓名</th><th>方式</th><th>结果</th></tr></table>"
"<span id='pg'></span></div>"
"<div class='card'><b>设备管理</b><div id='dev'>…</div>"
"<button onclick='ntp()'>NTP 时间矫正</button><span id='npm'></span></div>"
"<div class='card'><b>视频监控</b><div id='video'>摄像头链路接入后此处显示 RTSP/MJPEG 预览</div></div>"
"</div><script>"
"let TOKEN=sessionStorage.token||'';let S=null;"
"function hdr(){return {'X-Auth-Token':TOKEN,'Content-Type':'application/json'}}"
"function login(){fetch('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},"
"body:JSON.stringify({user:u.value,pwd:p.value})}).then(r=>r.json()).then(j=>{"
"if(j.token){TOKEN=j.token;sessionStorage.token=TOKEN;boot()}else lm.innerText=j.msg||'失败'})}"
"function boot(){document.getElementById('login').style.display='none';"
"document.getElementById('app').style.display='block';loadDevice();loadLogs();ws()}"
"function ws(){S=new WebSocket('ws://'+location.host+'/api/ws');"
"S.onopen=()=>{ws.innerText='已连接';setInterval(()=>{try{S.send('ping')}catch(e){}},2000)};"
"S.onclose=()=>ws.innerText='断开';"
"S.onmessage=e=>{let j=JSON.parse(e.data);if(j.type=='auth')"
"live.innerHTML+=`<div class='${j.result==0?'ok':'err'}'>${j.time} ${j.user_name||'陌生人'} "
"${j.result==0?'验证通过':'验证失败'}(${j.method})</div>`;"
"if(j.type=='ntp')live.innerHTML+=`<div>NTP: ${j.ok?'成功':'失败'}</div>`}}"
"function loadLogs(){let q='?';if(from.value)q+='from='+from.value+'&';"
"if(to.value)q+='to='+to.value;fetch('/api/logs'+q,{headers:hdr()}).then(r=>r.json())"
".then(j=>{let t='<tr><th>时间</th><th>ID</th><th>姓名</th><th>方式</th><th>结果</th></tr>';"
"j.logs.forEach(l=>{t+=`<tr><td>${l.time}</td><td>${l.user_id||'-'}</td><td>${l.user_name||'陌生人'}</td>"
"<td>${l.method_name}</td><td class='${l.result==0?'ok':'err'}'>${l.result_name}</td></tr>`});"
"document.getElementById('logs').innerHTML=t;document.getElementById('pg').innerText=`${j.page}/${j.pages} 共${j.total}条`})}"
"function loadDevice(){fetch('/api/device',{headers:hdr()}).then(r=>r.json())"
".then(j=>document.getElementById('dev').innerText=`版本 ${j.version} | 运行 ${j.uptime_s}s | 日志 ${j.log_total} 条`)}"
"function ntp(){document.getElementById('npm').innerText='执行中…';"
"fetch('/api/ntp',{method:'POST',headers:hdr()})"
".then(r=>r.json()).then(j=>document.getElementById('npm').innerText=j.ok?'成功':'失败(未联网?)')}"
"if(TOKEN)boot();else document.getElementById('login').style.display='block';"
"</script></body></html>";
